batch_size: 64
cellprob_threshold: 0.2
channel_labels:
- index: 0
  name: PomC
- index: 1
  name: DREADD
- index: 2
  name: Fos
- index: 3
  name: Gal
channels:
- 0
- 1
- 2
- 3
cpsam:
  advanced_filtering:
    abs_floor_percentile: 74
    foreground_block_size: 1001
    foreground_offset: 10
    snr_min: 2
  cellpose:
    channel: 2
    niter: 1000
    resize_max: 4096
    save_masks: true
    split_regions: false
  conditions:
    neg_pattern: Input_neg_
    pos_pattern: Input_pos_
  enable_advanced_filtering: true
  filters:
    intensity_threshold_factor: 0.92
    max_area: 8000
    max_circularity: 1
    max_hole_ratio: 0.7
    min_area: 20
    min_circularity: 0.01
  outputs:
    base_name: cell_analysis
  overlays:
    contour_color: magenta
    dpi: 300
    figsize:
    - 12
    - 12
    line_width: 1
    overlay_mode: contours
  processing:
    contrast_stretch: true
    intensity_threshold: 21
    merge_adjacent_cells: false
    remove_edge_cells: false
    split_area_multiplier: 2
    split_min_area: 0
    split_min_distance: 50
    split_rel_peak_threshold: 0.4
    split_touching_cells: true
    stretch_percentiles:
    - 1
    - 100
    tophat: true
    tophat_radius: 20
det_channel_selection:
- 2
det_script_path: ''
diameter: 20
flow_threshold: 0.32
input_tiffs_dir: /app/data/Input/TV2
model_type: cpsam
output_results_dir: /app/results/Test2
overlay_suffix: _overlay.png
save_overlay: true
testing:
  enabled: false
  samples_per_channel: 2
use_gpu: true
verbose: false
