analysis:
  enable_anova: false
auto_mag_from_path: false
batch_size: 4
cellprob_threshold: 0.2
channel_labels:
- index: 0
  name: Casp3
- index: 1
  name: Fos
- index: 2
  name: Gal
- index: 3
  name: DAPI
channel_levels:
- index: 0
  level: 5
- index: 1
  level: 5
- index: 2
  level: 5
- index: 3
  level: 5
channels:
- 0
- 1
- 2
- 3
clahe: true
clahe_clip_limit: 0.03
contrast_stretch: false
cpsam:
  advanced_filtering:
    abs_floor_percentile: 74
    background_radius: 50
    enable_advanced: false
    intensity_mode: global
    max_intensity_threshold: 0.1
    noise_radius: 25
    save_debug_images: false
    snr_min: 2
    snr_threshold: 2.5
    use_robust_normalization: false
  cell_filtering: {}
  cellpose:
    resize_max: 2048
  conditions: {}
  filters: {}
  microscope: {}
  overlay: {}
  preprocessing:
    clahe: true
    clahe_clip_limit: 0.03
    contrast_stretch: false
    tophat: false
    tophat_radius: 15
  processing: {}
  save_masks: false
  split_regions: false
  watershed_split:
    split_touching: false
cur_mag: 5
det_channel_selection:
- 2
det_script_path: ''
diameter: 0
flow_threshold: 0.32
image_aware_scaling: true
input_tiffs_dir: /app/data/Input/TV3_TIFF
microscope:
  current_magnification: 10
  reference_magnification: 10
model_type: cpsam
output_results_dir: /app/results/final/TV3_test7
ref_mag: 10
resize_max: 2048
save_overlay: false
testing:
  enabled: true
  levels:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  mode: advanced
  samples_per_channel: 1
  seed: null
  specific_image_neg: /app/data/Input/TV3_TIFF/Input_neg/DMH/O567_slice6_5x_stack.tif
  specific_image_pos: /app/data/Input/TV3_TIFF/Input_pos/Arc/O835_slice2_5x_stack.tif
tophat: false
tophat_radius: 15
use_gpu: true
verbose: false
