channel_colors:
- yellow
- green
- red
- red
channel_names: []
channels:
- 0
- 1
- 2
- 3
dtype: uint16
imagej_hyperstack: true
input_root: /app/data/Input/TV2_czi
output_base: /app/data/Input/TV2
overwrite: true
per_channel_normalize: true
rgb_channels:
- 0
- 1
- 2
- 3
save_color_composite: false
save_multichannel_colored_pages: false
save_ome_tiff_colors: true
save_per_channel: false
save_rgb_preview: false
save_stack_tiff: true
stack_layout: CYX
target_size: 2048
verbose: false
