channel_config:
- enabled: true
  index: 0
  name: PomC
- enabled: true
  index: 1
  name: DREADD
- enabled: true
  index: 2
  name: Fos
- enabled: true
  index: 3
  name: Gal
channels_limit: 4
combos_enabled:
- 2
- 3
- 4
dataset_name: ''
debug: true
detection:
  active_hsv_range_index: 0
fallback_from_overlays: true
paths:
  base_results_dir: /app/results/Test2
  output_dir: /app/results/Coex
save_composite_figure: true
selected_combos: []
testing:
  enabled: false
  samples_per_channel: 2
use_detection_masks: true
