auto_threshold: true
blend_base_color: '#0000ff'
blend_formats:
- png
- tiff
blend_other_color: '#80ff00'
blend_overlap_color: '#ff0000'
centroid_overlap_fraction: 0.5
channel_config:
- color: '#a358fe'
  enabled: true
  index: 0
  name: Casp3
- color: '#ffd500'
  enabled: true
  index: 1
  name: Fos
- color: '#24ff32'
  enabled: true
  index: 2
  name: Gal
- color: '#1f39ff'
  enabled: true
  index: 3
  name: DAPI
channels_limit: 4
coexpr_mode: blend
combos_enabled:
- 2
- 3
- 4
dataset_name: ''
input_dir: /app/results/final/TV3
output_dir: /app/results/final/CoexTV3
overlap_threshold: 30
overlay_formats:
- png
overlay_visualization:
  centroid_heatmap: true
  centroid_size: 3
  color_k2: '#ff0000'
  color_k3: '#ff0000'
  color_k4: '#ff0000'
  dpi: 600
  even_layout: grid
  figure_type: mask
  fill_alpha: 0.45
  overlay_style: filled
  show_only_coexpressing: true
  single_color: '#808080'
save_figure: true
selected_combos:
- - 0
  - 1
- - 0
  - 2
- - 0
  - 3
- - 1
  - 2
- - 1
  - 3
- - 2
  - 3
- - 0
  - 1
  - 2
- - 0
  - 1
  - 3
- - 0
  - 2
  - 3
- - 1
  - 2
  - 3
- - 0
  - 1
  - 2
  - 3
test_mode:
  seed: ''
  sweep_modes: []
  sweep_sample: ''
  type: 'off'
use_masks: true
