"""
tests/test_pipeline_service.py — unit tests for the new headless API layer.
"""
from __future__ import annotations

import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import yaml

from tests.fixtures.synthetic_cells import create_test_dataset
from src.api.pipeline_service import run_detection, run_full_pipeline


def _write_det_config(root: Path, input_pos: Path, input_neg: Path, output_root: Path) -> Path:
    cfg = {
        "paths": {
            "input_pos": str(input_pos),
            "input_neg": str(input_neg),
            "output_root": str(output_root),
        },
        "cellpose": {
            "model_name": "cyto2",
            "use_gpu": False,
            "diameter": 12,
            "flow_threshold": 0.4,
            "cellprob_threshold": 0.0,
            "save_masks": True,
            "split_regions": False,
            "channel": 0,
            "batch_size": 1,
            "resize_max": 512,
        },
        "filters": {
            "min_area": 10,
            "max_area": 500,
            "min_circularity": 0.0,
            "max_circularity": 1.0,
        },
        "outputs": {
            "base_name": "analysis_results",
            "create_overlays": False,
        },
        "analysis": {"enable_anova": False},
        "testing": {"enabled": True, "samples_per_channel": 2, "seed": 1},
    }
    p = root / "config_det_test.yaml"
    p.write_text(yaml.safe_dump(cfg), encoding="utf-8")
    return p


def _write_coexpr_config(output_root: Path) -> Path:
    output_root.mkdir(parents=True, exist_ok=True)
    cfg = {
        "input_dir": str(output_root),
        "output_dir": str(output_root / "Coex"),
        "channel_config": [
            {"index": 0, "name": "Glp1r", "enabled": True, "color": "#ff0000"},
            {"index": 1, "name": "PomC", "enabled": True, "color": "#00ff00"},
            {"index": 2, "name": "Gal", "enabled": True, "color": "#0000ff"},
        ],
        "coexpr_mode": "overlap",
        "overlap_threshold": 30,
        "centroid_overlap_fraction": 0.5,
        "selected_combos": [[0, 1], [0, 2], [1, 2], [0, 1, 2]],
        "combos_enabled": [2, 3],
        "use_masks": False,          # synthetic images: use overlays (masks not generated by default)
        "fallback_from_overlays": True,
        "save_figure": False,
        "test_mode": {"type": "off"},
    }
    p = output_root / "config_coexpr_test.yaml"
    p.write_text(yaml.safe_dump(cfg), encoding="utf-8")
    return p


def test_run_detection_service():
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        create_test_dataset(tmp_path, n_images=1, seed_offset=200)
        input_pos = tmp_path / "data" / "processed_tiffs" / "Input_pos"
        input_neg = tmp_path / "data" / "processed_tiffs" / "Input_neg"
        output_root = tmp_path / "results" / "final"
        cfg = _write_det_config(tmp_path, input_pos, input_neg, output_root)

        result = run_detection(cfg, save_masks=True)
        assert Path(result["master_csv"]).exists(), "master CSV missing"
        assert Path(result["animal_csv"]).exists(), "animal CSV missing"
        assert Path(result["condition_csv"]).exists(), "condition CSV missing"
        assert Path(result["summary_md"]).exists(), "summary markdown missing"


def test_run_full_pipeline_service():
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        create_test_dataset(tmp_path, n_images=1, seed_offset=300)
        input_pos = tmp_path / "data" / "processed_tiffs" / "Input_pos"
        input_neg = tmp_path / "data" / "processed_tiffs" / "Input_neg"
        output_root = tmp_path / "results" / "final"
        det_cfg = _write_det_config(tmp_path, input_pos, input_neg, output_root)
        coexpr_cfg = _write_coexpr_config(output_root)

        result = run_full_pipeline(det_cfg, coexpr_cfg, save_masks=True)
        assert Path(result["master_csv"]).exists()
        assert Path(result["coexpression"]["output_dir"]).exists()


if __name__ == "__main__":
    test_run_detection_service()
    test_run_full_pipeline_service()
    print("✅ pipeline service tests passed")
