"""
tests/test_pipeline_integration.py — integration test that runs the
synthetic dataset through detection + co-expression and checks outputs.
"""
from __future__ import annotations

import shutil
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pytest
import yaml

from tests.fixtures.synthetic_cells import create_test_dataset
from run_pipeline import main as run_pipeline_main
from src.coexpression import main as coexpression_main


def _write_det_config(root: Path, input_pos: Path, input_neg: Path, output_root: Path) -> Path:
    cfg = {
        "paths": {
            "input_pos": str(input_pos),
            "input_neg": str(input_neg),
            "output_root": str(output_root),
        },
        "cellpose": {
            "model_name": "cyto2",
            "use_gpu": False,
            "diameter": 12,
            "flow_threshold": 0.4,
            "cellprob_threshold": 0.0,
            "save_masks": True,
            "split_regions": False,
            "channel": 0,
            "batch_size": 1,
            "resize_max": 512,
        },
        "filters": {
            "min_area": 10,
            "max_area": 500,
            "min_circularity": 0.0,
            "max_circularity": 1.0,
        },
        "outputs": {
            "base_name": "analysis_results",
            "create_overlays": False,
        },
        "analysis": {"enable_anova": False},
        "testing": {"enabled": False},
    }
    p = root / "config_test.yaml"
    p.write_text(yaml.safe_dump(cfg), encoding="utf-8")
    return p


def _write_coexpr_config(output_root: Path) -> Path:
    cfg = {
        "input_dir": str(output_root),
        "output_dir": str(output_root / "Coex"),
        "channel_config": [
            {"index": 0, "name": "Glp1r", "enabled": True, "color": "#ff0000"},
            {"index": 1, "name": "PomC", "enabled": True, "color": "#00ff00"},
            {"index": 2, "name": "Gal", "enabled": True, "color": "#0000ff"},
        ],
        "coexpr_mode": "overlap",
        "overlap_threshold": 30,
        "centroid_overlap_fraction": 0.5,
        "selected_combos": [[0, 1], [0, 2], [1, 2], [0, 1, 2]],
        "combos_enabled": [2, 3],
        "use_masks": False,          # synthetic images: use overlays (masks not generated by default)
        "fallback_from_overlays": True,
        "save_figure": False,
        "test_mode": {"type": "off"},
    }
    p = output_root / "config_coexpr_test.yaml"
    p.write_text(yaml.safe_dump(cfg), encoding="utf-8")
    return p


def test_synthetic_pipeline_end_to_end():
    """Run detection and co-expression on synthetic data and assert expected outputs."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        create_test_dataset(tmp_path, n_images=2, seed_offset=100)

        input_pos = tmp_path / "data" / "processed_tiffs" / "Input_pos"
        input_neg = tmp_path / "data" / "processed_tiffs" / "Input_neg"
        output_root = tmp_path / "results" / "final"

        det_cfg = _write_det_config(tmp_path, input_pos, input_neg, output_root)

        # 1) Detection
        rc = run_pipeline_main(["--config", str(det_cfg), "--no-summary"])
        assert rc == 0, "detection pipeline failed"

        # check master CSV exists somewhere under output_root
        master_csv = output_root / "pos" / "All_Counts_Master.csv"
        if not master_csv.exists():
            master_csv = output_root / "All_Counts_Master.csv"
        assert master_csv.exists(), "All_Counts_Master.csv not generated"

        # 2) Co-expression
        coexpr_cfg = _write_coexpr_config(output_root)
        rc2 = coexpression_main(["--config", str(coexpr_cfg)])
        assert rc2 == 0, "co-expression step failed"

        coex_dir = output_root / "Coex"
        assert coex_dir.exists(), "co-expression output directory missing"

        csvs = list(coex_dir.rglob("*.csv"))
        assert len(csvs) > 0, "no co-expression CSV produced"

        # 3) Sanity: with 40 synthetic cells/channel we expect positive counts
        import pandas as pd
        df = pd.read_csv(master_csv)
        assert not df.empty, "master CSV is empty"
        assert "cell_count" in df.columns
        assert df["cell_count"].sum() > 0, "no cells detected"


if __name__ == "__main__":
    test_synthetic_pipeline_end_to_end()
    print("✅ pipeline integration test passed")
