dataset_name: ''
channels:
- index: 0
  name: PomC
  enabled: true
- index: 1
  name: DREADD
  enabled: true
- index: 2
  name: Fos
  enabled: true
- index: 3
  name: Gal
  enabled: true
combos_enabled:
- 2
selected_combos: []
overlay_params:
  dpi: 600
  line_width: 2
  figsize:
  - 12
  - 12
  colors_by_k:
    '2': red
    '3': magenta
    '4': cyan
  single_positive_color: gray
  base_channel_index: null
  figure_type: mask
  even_layout: grid
  overlay_style: mixed
  fill_alpha: 0.45
  save_centroid_heatmap: false
  centroid_marker_size: 80
coexpression:
  mode: blend
  centroid_max_distance: 8.0
  blend_base_color: '#0000ff'
  blend_other_color: '#ff0000'
  blend_overlap_color: '#ffff00'
  blend_overlap_fraction: 0.02
  centroid_overlap_fraction: 0.5
  blend_channel_colors:
    0: '#58fefb'
    1: '#ffd500'
    2: '#24ff32'
    3: '#ff1f80'
  sweep:
    enabled: false
    modes:
    - overlap
    - either
    - intersection
    sample_key: ''
